# Generated by Django 3.2.9 on 2022-02-18 01:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('published', models.DateField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('-----', 'Choose'), ('Action', 'Action'), ('Sci_Fi', 'Sci Fi'), ('Education', 'Education'), ('Fantasy', 'Fantasy')], default=None, max_length=50)),
                ('photoFile', models.ImageField(blank=True, upload_to='media/')),
                ('file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('author', models.CharField(default=None, max_length=300)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('published', models.DateField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('-----', 'Choose'), ('Action', 'Action'), ('Sci_Fi', 'Sci Fi'), ('Education', 'Education'), ('Fantasy', 'Fantasy')], default=None, max_length=50)),
                ('photoFile', models.ImageField(blank=True, upload_to='media/')),
                ('file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('published', models.DateField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('-----', 'Choose'), ('Action', 'Action'), ('Sci_Fi', 'Sci Fi'), ('Education', 'Education'), ('Fantasy', 'Fantasy')], default=None, max_length=50)),
                ('photoFile', models.ImageField(blank=True, upload_to='media/')),
                ('file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
                'index_together': {('user', 'book')},
            },
        ),
    ]
