# Generated by Django 3.2.9 on 2022-02-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('published', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
